
thread1:
	g++ -O3 -g -lpthread -DSMART_POLITE ./thread1.cpp && ./a.out

map:
	g++ -O1 -g -lpthread -DSMART_POLITE ./map.cpp && ./a.out

consistent_hash:
	clang++ -std=c++11 -stdlib=libc++ ./consistent_hash.cc && ./a.out

lock_problem_cond:
	clang++ -std=c++11 -stdlib=libc++ ./lock_problem_cond.cpp && ./a.out
	#g++ --std=c11 -lpthread -DSMART_POLITE ./lock_problem_cond.cpp && ./a.out

data_struct:
	g++ -O1 -g -lpthread -DSMART_POLITE ./data_struct.cpp && ./a.out

lock_problem_dining:
	g++ -lpthread -DSMART_POLITE ./lock_problem_dining.cpp && ./a.out

lock_problem:
	g++ -lpthread ./lock_problem.cpp  && ./a.out

shared_ptr_multi_thread:
	g++ -lpthread ./shared_ptr_multi_thread.cpp  && ./a.out
