
lock_problem_cond:
	clang++ -std=c++11 -stdlib=libc++ ./lock_problem_cond.cpp && ./a.out
	#g++ --std=c11 -lpthread -DSMART_POLITE ./lock_problem_cond.cpp && ./a.out

data_struct:
	g++ -lpthread -DSMART_POLITE ./data_struct.cpp && ./a.out

lock_problem_dining:
	g++ -lpthread -DSMART_POLITE ./lock_problem_dining.cpp && ./a.out

lock_problem:
	g++ -lpthread ./lock_problem.cpp  && ./a.out

shared_ptr_multi_thread:
	g++ -lpthread ./shared_ptr_multi_thread.cpp  && ./a.out
