CREATE TABLE `md_d_date_dm_dim`(
   `calendar_date` string COMMENT '日期', 
   `previous_day` string COMMENT '前一天日期', 
   `next_day` string COMMENT '后一天日期', 
   `year` string COMMENT '年份', 
   `month` string COMMENT '月份', 
   `is_holiday` string COMMENT '是否节假日', 
   `year_month` string COMMENT '年月', 
   `is_in_7days` string COMMENT '是否在7天内', 
   `is_in_30days` string COMMENT '是否在30天内', 
   `is_in_14days` string COMMENT '是否在14天内', 
   `is_in_60days` string COMMENT '是否在60天内', 
   `is_in_90days` string COMMENT '是否在90天内', 
   `is_cur_day` string COMMENT '是否本日', 
   `is_cur_week` string COMMENT '是否本周', 
   `is_cur_mon` string COMMENT '是否本月', 
   `is_cur_quat` string COMMENT '是否本季', 
   `is_cur_year` string COMMENT '是否本年', 
   `stat_date` string COMMENT '当前日期', 
   `year_days` decimal(38,2) COMMENT '年天数', 
   `now_year_days` decimal(38,2) COMMENT '截止当前年天数', 
   `is_in_5days` string COMMENT '是否在5天内', 
   `is_in_15days` string COMMENT '是否在15天内', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`calendar_date`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                        )
DISTRIBUTED BY HASH(`calendar_date`) BUCKETS 10


PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_cust_dim`(
   `cust_no` string COMMENT '客户号', 
   `org_id` string COMMENT '客户归属行', 
   `dat_cust_open` string COMMENT '客户开户时间', 
   `cust_open_org` string COMMENT '客户开户机构/客户开户行', 
   `con_birth_dt` string COMMENT '出生年月', 
   `con_sex_mf` string COMMENT '客户性别', 
   `cust_age` string COMMENT '客户年龄', 
   `asset_level_manage` string COMMENT '财富管理客户分层', 
   `cust_asset_level` string COMMENT '客户资产分层', 
   `cust_type` string COMMENT '客户类型', 
   `risk_level` string COMMENT '风险评估', 
   `zt_flag` string COMMENT '综拓客户标识', 
   `yc_flag` string COMMENT '远程客户标志', 
   `sf_flag` string COMMENT '是否三管签约客户/是否银证客户', 
   `cust_manager` string COMMENT '客户管户人', 
   `cust_manager_flag` string COMMENT '是否管户客户', 
   `small_micro_flag` string COMMENT '是否小微客户', 
   `sx_flag` string COMMENT '是否寿险客户', 
   `payroll_his_flag` string COMMENT '是否历史代发客户', 
   `payroll_flag` string COMMENT '是否代发客户', 
   `payroll_current_mon_flag` string COMMENT '是否本月代发客户', 
   `wx_bind_date` string COMMENT '微信绑定账户时间', 
   `wx_bind_flag` string COMMENT '微信绑定账户标志', 
   `card_level` string COMMENT '客户持卡等级', 
   `ck_cust_flag` string COMMENT '是否财客(私财:财客及以上客户)', 
   `sz_cust_flag` string COMMENT '是否私钻客户(私钻及以上客户)', 
   `sh_cust_flag` string COMMENT '是否私行客户', 
   `sha_cust_flag` string COMMENT '是否私行A类客户', 
   `shb_cust_flag` string COMMENT '是否私行B类客户', 
   `gdqy_cust_flag` string COMMENT '是否滚动千元户', 
   `gdwy_cust_flag` string COMMENT '是否滚动万元户', 
   `gjz_cust_flag` string COMMENT '是否高净值客户', 
   `super_c_cust_flag` string COMMENT '是否超高端C类客户', 
   `super_b_cust_flag` string COMMENT '是否超高端B类客户', 
   `super_a_cust_flag` string COMMENT '是否超高端A类客户', 
   `gh_channel` string COMMENT '管户渠道', 
   `mhr_org_id` string COMMENT '管户人归属机构ID', 
   `mhr_team_id` string COMMENT '管户人归属团队ID', 
   `mhr_team_name` string COMMENT '管户人归属团队名称', 
   `mhr_channel_id` string COMMENT '管户人归属渠道ID', 
   `mhr_channel_name` string COMMENT '管户人归属渠道名称', 
   `asset_level_manage_lm` string COMMENT '上月财富管理客户分层', 
   `asset_level_manage_ly` string COMMENT '上年财富管理客户分层', 
   `cust_1st_flag` string COMMENT '一类户标识', 
   `cust_2nd_flag` string COMMENT '二类户标识', 
   `cust_3rd_flag` string COMMENT '三类户标识', 
   `sk_new_flag` string COMMENT '双卡双新标识', 
   `jj_new_flag` string COMMENT '借记新户标识', 
   `xy_new_flag` string COMMENT '信用卡新户标识', 
   `fzh_flag` string COMMENT '分支行渠道标识', 
   `zk_flag` string COMMENT '重客标志', 
   `ccjlb_cust_flag` string COMMENT '传承俱乐部客户标志', 
   `ccjlb_agent_flag` string COMMENT '俱乐部会员标志', 
   `agent_no` string COMMENT '会员号', 
   `agent_pb_no` string COMMENT '会员所属金融顾问', 
   `agent_org_id` string COMMENT '会员所属机构', 
   `ccjlb_cust_list_add_type` string COMMENT '俱乐部私钻客户本年获客流失类型', 
   `potential_flag` string COMMENT '潜力菁英标志', 
   `agent_level` string COMMENT '会员等级', 
   `agent_yp_level` string COMMENT '会员预判等级', 
   `agent_asset_level` string COMMENT '会员财富层级', 
   `new_agent_flag` string COMMENT '本年新会员标志', 
   `agent_level_desc` string COMMENT '会员岗位描述', 
   `agent_status_desc` string COMMENT '会员在职状态(试用,在职,离职)', 
   `agent_post_flag` string COMMENT '会员离职标志', 
   `qualify_investor_flag` string COMMENT '客户合格投资者标签', 
   `qlsz_flag` string COMMENT '潜力私钻客户标志', 
   `t0_cust_flag` string COMMENT 'T0客户标志', 
   `t1_cust_flag` string COMMENT 'T1客户标志', 
   `t2_cust_flag` string COMMENT 'T2客户标志', 
   `mon_touch_flag` string COMMENT '本月接触标志', 
   `hold_bxjxt_flag` string COMMENT '保险金信托客户标志', 
   `pb_cust_manage_flag` string COMMENT '三点一线对齐客户标志', 
   `zj_pb_cust_manage_flag` string COMMENT '管户人是否综金PB标志', 
   `cf_asset_level_name` string COMMENT '财富管理分层名称', 
   `cust_asset_level_name` string COMMENT '客户资产分层名称', 
   `new_cust_flag` string COMMENT '本年新客标识', 
   `rj_flag` string COMMENT '是否入金', 
   `app_fst_login_date` string COMMENT '首次登录口袋APP的日期', 
   `qw_cust_flag` string COMMENT '是否企微客户', 
   `group_cust_type` string COMMENT '集团客户最高账户类型', 
   `qw_gh_flag` string COMMENT '是否管户客户(企微)', 
   `yb_flag` string COMMENT '是否银保客户', 
   `acct_vail_cust_flag` string COMMENT '账户有效客户标识', 
   `mtd_actv_cust_flag` string COMMENT '客户动账月活标志', 
   `qtd_actv_cust_flag` string COMMENT '客户动账季活标志', 
   `ytd_actv_cust_flag` string COMMENT '客户动账年活标志', 
   `iiact_uplvl_cust_flag` string COMMENT '二类户升级一类户客户标志', 
   `iiiact_uplvl_cust_flag` string COMMENT '三类户升级一类户客户标志', 
   `iiact_upopn_cust_flag` string COMMENT '二类户开立一类户客户标志', 
   `iiiact_upopn_cust_flag` string COMMENT '二类户开立一类户客户标志', 
   `nw_sw_desc` string COMMENT '客户管户内外勤标识', 
   `vail_cust_manager_flag` string COMMENT '真实(有效)管户人标识', 
   `cust_manager_ttk_flag` string COMMENT '厅堂宽口径', 
   `cust_manager_ttz_flag` string COMMENT '厅堂窄口径', 
   `quali_type_jj_flag` string COMMENT '客户管户是否基金持证', 
   `lcjl_flag` string COMMENT '理财金领_客群标志', 
   `djg_flag` string COMMENT '董监高_客群标志', 
   `cgjz_flag` string COMMENT '超高净值_客群标志', 
   `fyzln_flag` string COMMENT '富裕中老年_客群标志', 
   `jmsk_flag` string COMMENT '精明熟客客_客群标志', 
   `xqyz_flag` string COMMENT '小企业主_客群标志', 
   `ycyz_flag` string COMMENT '有车一族_客群标志', 
   `nqcr_flag` string COMMENT '年轻潮人_客群标志', 
   `cf_asset_level_range` string COMMENT '财富管理客户资产等级范围', 
   `mtd_pay_cust_flag` string COMMENT '财富管理客户资产等级范围', 
   `qtd_pay_cust_flag` string COMMENT '客户支付季活标志', 
   `ytd_pay_cust_flag` string COMMENT '客户支付年活标志', 
   `yb_five_star_lvl` string COMMENT '银保五星客户等级', 
   `shgh_flag` string COMMENT '是否私行中心管户', 
   `y_new_cust_flag` string COMMENT '本年新客标识(剔除无效户)', 
   `m_new_cust_flag` string COMMENT '本月新客标识(剔除无效户)', 
   `hold_card_type` string COMMENT '持卡类型', 
   `qr_new_flag` string COMMENT '汽融双新标识', 
   `qr_m_flag` string COMMENT '汽融客户标识(未结清或本年结清)', 
   `xj_new_flag` string COMMENT '消金双新标识', 
   `xj_m_flag` string COMMENT '消金客户标识(未结清或本年结清)', 
   `credit_channl_flag` string COMMENT '信用卡渠道', 
   `last_30d_login_flag` string COMMENT '口袋app活跃30天用户', 
   `gd5wy_cust_flag` string COMMENT '是否滚动5万元户', 
   `ds_cust_flag` string COMMENT '是否顶私客户', 
   `cust_asset_level_ds` string COMMENT '客户资产分层_顶私', 
   `hk_ls_type_mon` string COMMENT '顶私获客流失类型(较上月末)', 
   `hk_ls_type_year` string COMMENT '顶私获客流失类型(较上年末)', 
   `sh_gh_type` string COMMENT '私行管户类型', 
   `xyk_flag` string COMMENT '信用卡渠道标识T-2(双卡客户+信用卡MGM+被动注销)', 
   `zt_all_flag` string COMMENT '大综拓渠道标识T-2(综拓老渠道+一户通标识)', 
   `sd_flag` string COMMENT '收单渠道标识T-2', 
   `df_sub_lc_flag` string COMMENT '代发渠道标识T-2(客群)', 
   `kfyh_flag` string COMMENT '开放银行渠道标识T-2', 
   `wdjd_flag` string COMMENT '网点进店渠道标识T-2(本年)', 
   `yz_flag` string COMMENT '银证渠道标识T-2', 
   `non_zero_flag` string COMMENT '非零资产客户标识', 
   `ops_wdsthk_flag` string COMMENT '网点生态渠道标识', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`cust_no`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`cust_no`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_fund_cust_dim`(
   `cust_no` string COMMENT '客户号', 
   `fhb_hold_ppc` string COMMENT '公募非货基持仓PPC分层', 
   `gmonline_flag` string COMMENT '公募线上客群标签', 
   `aum_hold_ppc` string COMMENT 'AUM持仓PPC分层', 
   `ck_hold_ppc` string COMMENT '存款持仓PPC分层', 
   `dqlc_hold_ppc` string COMMENT '定期理财持仓PPC分层', 
   `hqlc_hold_ppc` string COMMENT '活期理财持仓PPC分层', 
   `sm_hold_ppc` string COMMENT '私募持仓PPC分层', 
   `cust_manager_offline_chnl_type` string COMMENT '管户线下渠道类型', 
   `last_30d_fund_act_flag` string COMMENT '近30天访问基金页面活跃标识', 
   `accompany_act_flag` string COMMENT '历史访问陪伴活跃标识', 
   `last_30d_accompany_act_flag` string COMMENT '近30天访问陪伴活跃标识', 
   `gmfhb_ly_hold_bal_lvl` string COMMENT '去年末公募非货基持仓金额分层', 
   `gmfhb_hold_bal_lvl` string COMMENT '当前公募非货基持仓金额分层', 
   `gmfhb_dt_hold_bal_lvl` string COMMENT '当前公募非货基定投持仓金额分层', 
   `gmfhb_dt_execute_cnt_lvl` string COMMENT '当前公募非货基定投持有正常协议数分层', 
   `gmfhb_pb_vaild_flag` string COMMENT '破冰有效户标识(T-2)', 
   `offer_gmfhb_pb_flag` string COMMENT '钩子破冰客户标识(T-2)', 
   `gmfhb_aum_rate_lvl` string COMMENT '非货基持仓和AUM的占比分层', 
   `um_self_flag` string COMMENT '管户本人客户号标识', 
   `gmfhb_vaild_hold_flag` string COMMENT '公募非货基有效持仓标识', 
   `cust_age_level` string COMMENT '客户年龄分层', 
   `sp_uv_flag` string COMMENT '当月是否访问资讯', 
   `sp_cnt_level` string COMMENT '当月资讯访问篇数分层', 
   `zb_uv_flag` string COMMENT '当月是否访问直播', 
   `zb_cnt_level` string COMMENT '当月直播访问篇数分层', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`cust_no`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`cust_no`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_fund_prod_dim`(
   `prod_id` string COMMENT '产品代码（后端）', 
   `fund_daily_profit_flag` string COMMENT '日日盈产品标识', 
   `fund_gm365_flag` string COMMENT '公募365产品标识', 
   `fund_prod_managers_name` string COMMENT '基金经理人名称组', 
   `fund_pockets_type` string COMMENT '钱袋子标识', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`prod_id`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`prod_id`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_org_dim`(
   `branch_no` string COMMENT '机构号', 
   `branch_name` string COMMENT '机构名称', 
   `branch_type` string COMMENT '机构类型', 
   `branch01_no` string COMMENT '一级机构号', 
   `branch01_name` string COMMENT '一级机构名称', 
   `branch02_no` string COMMENT '二级机构号、区域号', 
   `branch02_name` string COMMENT '二级机构名称、区域名称', 
   `branch03_no` string COMMENT '三级机构号、一级分行机构号', 
   `branch03_name` string COMMENT '三级机构名称、一级分行机构名称', 
   `branch04_no` string COMMENT '四级机构号、二级分行机构号', 
   `branch04_name` string COMMENT '四级机构名称、二级分行机构名称', 
   `branch05_no` string COMMENT '五级机构号、一级支行机构号', 
   `branch05_name` string COMMENT '五级机构名称、一级支行机构名称', 
   `branch06_no` string COMMENT '六级机构号、二级支行机构号', 
   `branch06_name` string COMMENT '六级机构名称、二级支行机构名称', 
   `org_province` string COMMENT '所属省份', 
   `group_name` string COMMENT '所属组名称', 
   `sh_group_name` string COMMENT '私行中心分组名称', 
   `zh_group_name` string COMMENT '归属支行AUM规模分组', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`branch_no`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`branch_no`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_prod_dim`(
   `prod_id` string COMMENT '产品编号', 
   `prod_name` string COMMENT '产品名称', 
   `prod_id_new` string COMMENT '新产品码', 
   `first_prod_ind` string COMMENT '一级产品编号', 
   `first_prod_name` string COMMENT '一级产品名称', 
   `snd_prod_ind` string COMMENT '二级产品编号', 
   `snd_prod_name` string COMMENT '二级产品名称', 
   `third_prod_ind` string COMMENT '三级产品编号', 
   `third_prod_name` string COMMENT '三级产品名称', 
   `fourth_prod_ind` string COMMENT '四级产品编号', 
   `fourth_prod_name` string COMMENT '四级产品名称', 
   `src_prod_ind` string COMMENT '源产品编号', 
   `source_sys` string COMMENT '源系统', 
   `front_lv4` string COMMENT '产品货架四级代码', 
   `front_lv4_name` string COMMENT '产品货架四级代码名称', 
   `prod_lc_des` string COMMENT '新老理财描述', 
   `front_prod_ind` string COMMENT '前端产品编号', 
   `yxjj_flag` string COMMENT '优选基金', 
   `history_yxjj_flag` string COMMENT '历史优选基金产品标志', 
   `lab_base_fin_flg` string COMMENT '基础理财标志', 
   `lab_fhj_corp_flg` string COMMENT '公募非货基标志', 
   `lab_incl_right_flg` string COMMENT '含权标志', 
   `prod_status` string COMMENT '产品状态', 
   `prod_nav` string COMMENT '产品净值', 
   `prod_nav_date` string COMMENT '产品净值日期', 
   `ipo_start_date` string COMMENT '募集开始日期', 
   `ipo_end_date` string COMMENT '募集结束日期', 
   `estab_date` string COMMENT '产品成立日期', 
   `risk_level` string COMMENT '风险等级', 
   `prd_sponsor` string COMMENT '产品发起人', 
   `prd_trustee` string COMMENT '产品托管人', 
   `prd_manager` string COMMENT '产品管理人', 
   `manager_shortname` string COMMENT '产品管理人简称', 
   `manager_name` string COMMENT '产品管理人名称', 
   `ta_code` string COMMENT '基金公式TA代码', 
   `ta_name` string COMMENT '基金公司简称', 
   `totalquota` string COMMENT '产品总额度', 
   `remainquota` string COMMENT '总行剩余可用额度', 
   `investterm` string COMMENT '投资期限', 
   `perform_benchmark` string COMMENT '业绩比较基准', 
   `investtermday` string COMMENT '产品久期(货架)', 
   `ls_fd_flg` string COMMENT '定存标志(基础零售)', 
   `ls_base_fin_flg` string COMMENT '基础理财标志(基础零售)', 
   `ls_fhj_corp_flg` string COMMENT '公募非货基标志(基础零售)', 
   `ma_key` string COMMENT '财富号代码', 
   `ma_name` string COMMENT '财富号名称', 
   `ck_prod_dl` string COMMENT '存款产品大类', 
   `ck_prod_xl` string COMMENT '存款产品小类', 
   `third_gushouplus_lvl` string COMMENT '三级带(公募固收+)分类名称', 
   `third_gushouplus_ind` string COMMENT '三级带(公募固收+)分类代码', 
   `fund_ac_type_flag` string COMMENT '公募区分AC类标识', 
   `fund_base_debt_flag` string COMMENT '公募之标债标识', 
   `fund_gm_more_flag` string COMMENT '公募含标债产品标识(常规公募+标债产品包)', 
   `fund_gushouplus_flag` string COMMENT '固收标识', 
   `fund_sysj_flag` string COMMENT '收益升级产品标识', 
   `fund_sdy_flag` string COMMENT '道盈产品标识', 
   `fund_sdy_snd_name` string COMMENT '赛道盈二级产品分类名称', 
   `fund_wjl_flag` string COMMENT '公募稳健产品标识', 
   `fund_fof_flag` string COMMENT 'FOF基金产品标识', 
   `prod_xl3` string COMMENT '基础理财标志(不含外部理财子)', 
   `prod_xl4` string COMMENT '基础理财标志(含外部理财子)', 
   `prod_included_flag` string COMMENT '含权理财标志', 
   `duration_section` string COMMENT '久期区间', 
   `cash_plus_flag` string COMMENT '是否现金加产品', 
   `three_mon_flag` string COMMENT '是否三个月理财产品', 
   `sm_bz_name` string COMMENT '私募周周标债名称', 
   `sm_prod_type` string COMMENT '私募新分类', 
   `lc_prod_dl` string COMMENT '理财新大类', 
   `lc_prod_xl` string COMMENT '理财新小类', 
   `prod_duran_day` string COMMENT '产品久期', 
   `total_quota` decimal(16,2) COMMENT '总发行额度', 
   `used_quota` decimal(16,2) COMMENT '已使用总额度', 
   `remain_quota` decimal(17,2) COMMENT '剩余额度', 
   `dt` date COMMENT 'dt')
 
         ENGINE=OLAP
DUPLICATE KEY(`prod_id`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`prod_id`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_prod_fund_buy_order_stat`(
 `serial_no` string COMMENT '订单流水号',
 `tx_type_desc` string COMMENT '交易类型(区分普通购买或定投购买)',
 `trans_type` string COMMENT '交易类型(区分首发、定投、持盈)',
 `cust_no` string COMMENT '客户号',
 `prod_id` string COMMENT '产品长编码(后端)',
 `tx_date` date COMMENT '下单日期(日期格式)',
 `cfm_date` date COMMENT '成交日期(日期格式)',
 `tx_amt_rmb` decimal(34,9) COMMENT '购买金额(折人民币)',
 `asso_serial` string COMMENT '定投协议号',
 `cfm_amt_rmb` decimal(33,9) COMMENT '成交金额(折人民币)',
 `bank_charge` decimal(16,2) COMMENT '手续费',
 `add_upd_saler` string COMMENT '推荐人UM（考虑补录）',
 `trade_dt_flag` string COMMENT '交易式定投标识Y/N',
 `fh_org_id` string COMMENT '战报分行机构(补录,推荐人>管户>客户归属)',
 `online_offline_flag` string COMMENT '线上线下远程标识(不考虑补录)',
 `tx_dt` string COMMENT '下单日期(字符格式)',
 `cfm_dt` string COMMENT '成交日期(字符格式)',
 `scheme_flag` string COMMENT '组合标识Y/N',
 `yxjj_buy_flag` string COMMENT '作为优选产品下单被购买标识Y/N',
 `time_on_offline_flag` string COMMENT '弃用',
 `tx_dt_month` string COMMENT '交易日期(月)',
 `online_offline_add_flag` string COMMENT '线上线下远程标识(考虑补录)',
 `fh_org_id_bak` string COMMENT '战报分行机构(不补录,推荐人>管户>客户归属)',
 `zh_org_id_bak` string COMMENT '战报支行机构(不补录,仅推荐人非pb)',
 `sh_gh_org_id_bak` string COMMENT '战报支行机构(不补录,推荐人>管户>客户归属)',
 `sh_org_id_bak` string COMMENT '战报私行机构(不补录，推荐人pb>管户人pb)',
 `gr_org_id_bak` string COMMENT '战报个人机构(不补录，仅推荐人)',
 `zh_org_id` string COMMENT '战报支行机构(补录,仅推荐人非pb)',
 `sh_gh_org_id` string COMMENT '战报私行机构(补录，推荐人pb>管户人pb)',
 `sh_org_id` string COMMENT '战报私行机构(补录，推荐人pb)',
 `gr_org_id` string COMMENT '战报个人机构(补录，仅推荐人)',
 `jzxt_fund_flag` string COMMENT '家族信托投配公募标识',
 `cfm_serial_flag` string COMMENT '成交订单标识Y/N',
 `add_upd_saler_bak` string COMMENT '增加推荐人(不补录)',
 `his_org_id_pms` string COMMENT '时点客户归属行机构',
 `buy_sign_m_flag` string COMMENT '当月购买当月签订标识',
 `fund_pockets_type` string COMMENT '公募钱袋子类型',
 `fund_trans_mode` string COMMENT '区分直连和非直连类型',
 `sell_code_channel_name` string COMMENT '分销渠道名称', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`serial_no`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`serial_no`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)CREATE TABLE `md_d_pw_user_dim`(
   `user_id` string COMMENT '员工号', 
   `user_name` string COMMENT '员工姓名', 
   `user_status` string COMMENT '员工状态', 
   `user_type` string COMMENT '员工类型', 
   `org_id` string COMMENT '所属机构', 
   `channel_id` string COMMENT '渠道号', 
   `channel_name` string COMMENT '渠道名称', 
   `dept_no` string COMMENT '部门编号', 
   `dept_name` string COMMENT '部门名称', 
   `team_id` string COMMENT '团队ID', 
   `team_name` string COMMENT '团队名称', 
   `center_id` string COMMENT '私行中心', 
   `center_name` string COMMENT '私行中心名称', 
   `user_level` string COMMENT '职级', 
   `in_date` string COMMENT '入司时间', 
   `out_date` string COMMENT '离职时间', 
   `user_sex` string COMMENT '性别', 
   `user_age` string COMMENT '年龄', 
   `birthday` string COMMENT '生日', 
   `birthplace` string COMMENT '出生地点', 
   `nativeplace` string COMMENT '籍贯', 
   `address` string COMMENT '地址', 
   `postal` string COMMENT '邮编', 
   `eng_name` string COMMENT '英文名', 
   `pab_code` string COMMENT '平安员工编号', 
   `post_date` string COMMENT '入职时间', 
   `posn_dt` string COMMENT '入岗日期', 
   `mar_status` string COMMENT '婚姻状况', 
   `mar_status_desc` string COMMENT '婚姻状况描述', 
   `school` string COMMENT '毕业院校', 
   `edu_lvl_achv` string COMMENT '最高学历', 
   `nation` string COMMENT '民族', 
   `nation_desc` string COMMENT '民族描述', 
   `party_id` string COMMENT '政治面貌', 
   `party_desc` string COMMENT '政治面貌描述', 
   `lc_quali_flag` string COMMENT '是否有理财销售资质', 
   `fund_quali_flag` string COMMENT '是否有基金销售资质', 
   `ins_quali_flag` string COMMENT '是否有保险销售资质', 
   `is_branch_flag` string COMMENT '是否归属分支行', 
   `is_pb_flag` string COMMENT '是否归属私行中心', 
   `nw_sw` string COMMENT '内外勤类别', 
   `nw_sw_desc` string COMMENT '内外勤中文描述', 
   `agent_um` string COMMENT '人员UM号', 
   `realy_gh_flag` string COMMENT '真实管户标识', 
   `valid_gh_flag` string COMMENT '有效管户标识', 
   `realy_zy_flag` string COMMENT '真实职员标识', 
   `dt` date COMMENT 'dt')
ENGINE=OLAP
DUPLICATE KEY(`user_id`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`user_id`) BUCKETS 10

PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)
