CREATE TABLE `md_d_pw_prod_dim`(
   `prod_id` string COMMENT '产品编号', 
   `prod_name` string COMMENT '产品名称', 
   `prod_id_new` string COMMENT '新产品码', 
   `first_prod_ind` string COMMENT '一级产品编号', 
   `first_prod_name` string COMMENT '一级产品名称', 
   `snd_prod_ind` string COMMENT '二级产品编号', 
   `snd_prod_name` string COMMENT '二级产品名称', 
   `third_prod_ind` string COMMENT '三级产品编号', 
   `third_prod_name` string COMMENT '三级产品名称', 
   `fourth_prod_ind` string COMMENT '四级产品编号', 
   `fourth_prod_name` string COMMENT '四级产品名称', 
   `src_prod_ind` string COMMENT '源产品编号', 
   `source_sys` string COMMENT '源系统', 
   `front_lv4` string COMMENT '产品货架四级代码', 
   `front_lv4_name` string COMMENT '产品货架四级代码名称', 
   `prod_lc_des` string COMMENT '新老理财描述', 
   `front_prod_ind` string COMMENT '前端产品编号', 
   `yxjj_flag` string COMMENT '优选基金', 
   `history_yxjj_flag` string COMMENT '历史优选基金产品标志', 
   `lab_base_fin_flg` string COMMENT '基础理财标志', 
   `lab_fhj_corp_flg` string COMMENT '公募非货基标志', 
   `lab_incl_right_flg` string COMMENT '含权标志', 
   `prod_status` string COMMENT '产品状态', 
   `prod_nav` string COMMENT '产品净值', 
   `prod_nav_date` string COMMENT '产品净值日期', 
   `ipo_start_date` string COMMENT '募集开始日期', 
   `ipo_end_date` string COMMENT '募集结束日期', 
   `estab_date` string COMMENT '产品成立日期', 
   `risk_level` string COMMENT '风险等级', 
   `prd_sponsor` string COMMENT '产品发起人', 
   `prd_trustee` string COMMENT '产品托管人', 
   `prd_manager` string COMMENT '产品管理人', 
   `manager_shortname` string COMMENT '产品管理人简称', 
   `manager_name` string COMMENT '产品管理人名称', 
   `ta_code` string COMMENT '基金公式TA代码', 
   `ta_name` string COMMENT '基金公司简称', 
   `totalquota` string COMMENT '产品总额度', 
   `remainquota` string COMMENT '总行剩余可用额度', 
   `investterm` string COMMENT '投资期限', 
   `perform_benchmark` string COMMENT '业绩比较基准', 
   `investtermday` string COMMENT '产品久期(货架)', 
   `ls_fd_flg` string COMMENT '定存标志(基础零售)', 
   `ls_base_fin_flg` string COMMENT '基础理财标志(基础零售)', 
   `ls_fhj_corp_flg` string COMMENT '公募非货基标志(基础零售)', 
   `ma_key` string COMMENT '财富号代码', 
   `ma_name` string COMMENT '财富号名称', 
   `ck_prod_dl` string COMMENT '存款产品大类', 
   `ck_prod_xl` string COMMENT '存款产品小类', 
   `third_gushouplus_lvl` string COMMENT '三级带(公募固收+)分类名称', 
   `third_gushouplus_ind` string COMMENT '三级带(公募固收+)分类代码', 
   `fund_ac_type_flag` string COMMENT '公募区分AC类标识', 
   `fund_base_debt_flag` string COMMENT '公募之标债标识', 
   `fund_gm_more_flag` string COMMENT '公募含标债产品标识(常规公募+标债产品包)', 
   `fund_gushouplus_flag` string COMMENT '固收标识', 
   `fund_sysj_flag` string COMMENT '收益升级产品标识', 
   `fund_sdy_flag` string COMMENT '道盈产品标识', 
   `fund_sdy_snd_name` string COMMENT '赛道盈二级产品分类名称', 
   `fund_wjl_flag` string COMMENT '公募稳健产品标识', 
   `fund_fof_flag` string COMMENT 'FOF基金产品标识', 
   `prod_xl3` string COMMENT '基础理财标志(不含外部理财子)', 
   `prod_xl4` string COMMENT '基础理财标志(含外部理财子)', 
   `prod_included_flag` string COMMENT '含权理财标志', 
   `duration_section` string COMMENT '久期区间', 
   `cash_plus_flag` string COMMENT '是否现金加产品', 
   `three_mon_flag` string COMMENT '是否三个月理财产品', 
   `sm_bz_name` string COMMENT '私募周周标债名称', 
   `sm_prod_type` string COMMENT '私募新分类', 
   `lc_prod_dl` string COMMENT '理财新大类', 
   `lc_prod_xl` string COMMENT '理财新小类', 
   `prod_duran_day` string COMMENT '产品久期', 
   `total_quota` decimal(16,2) COMMENT '总发行额度', 
   `used_quota` decimal(16,2) COMMENT '已使用总额度', 
   `remain_quota` decimal(17,2) COMMENT '剩余额度', 
   `dt` date COMMENT 'dt')
 
         ENGINE=OLAP
DUPLICATE KEY(`prod_id`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`prod_id`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)