CREATE TABLE `md_d_pw_cust_dim`(
   `cust_no` string COMMENT '客户号', 
   `org_id` string COMMENT '客户归属行', 
   `dat_cust_open` string COMMENT '客户开户时间', 
   `cust_open_org` string COMMENT '客户开户机构/客户开户行', 
   `con_birth_dt` string COMMENT '出生年月', 
   `con_sex_mf` string COMMENT '客户性别', 
   `cust_age` string COMMENT '客户年龄', 
   `asset_level_manage` string COMMENT '财富管理客户分层', 
   `cust_asset_level` string COMMENT '客户资产分层', 
   `cust_type` string COMMENT '客户类型', 
   `risk_level` string COMMENT '风险评估', 
   `zt_flag` string COMMENT '综拓客户标识', 
   `yc_flag` string COMMENT '远程客户标志', 
   `sf_flag` string COMMENT '是否三管签约客户/是否银证客户', 
   `cust_manager` string COMMENT '客户管户人', 
   `cust_manager_flag` string COMMENT '是否管户客户', 
   `small_micro_flag` string COMMENT '是否小微客户', 
   `sx_flag` string COMMENT '是否寿险客户', 
   `payroll_his_flag` string COMMENT '是否历史代发客户', 
   `payroll_flag` string COMMENT '是否代发客户', 
   `payroll_current_mon_flag` string COMMENT '是否本月代发客户', 
   `wx_bind_date` string COMMENT '微信绑定账户时间', 
   `wx_bind_flag` string COMMENT '微信绑定账户标志', 
   `card_level` string COMMENT '客户持卡等级', 
   `ck_cust_flag` string COMMENT '是否财客(私财:财客及以上客户)', 
   `sz_cust_flag` string COMMENT '是否私钻客户(私钻及以上客户)', 
   `sh_cust_flag` string COMMENT '是否私行客户', 
   `sha_cust_flag` string COMMENT '是否私行A类客户', 
   `shb_cust_flag` string COMMENT '是否私行B类客户', 
   `gdqy_cust_flag` string COMMENT '是否滚动千元户', 
   `gdwy_cust_flag` string COMMENT '是否滚动万元户', 
   `gjz_cust_flag` string COMMENT '是否高净值客户', 
   `super_c_cust_flag` string COMMENT '是否超高端C类客户', 
   `super_b_cust_flag` string COMMENT '是否超高端B类客户', 
   `super_a_cust_flag` string COMMENT '是否超高端A类客户', 
   `gh_channel` string COMMENT '管户渠道', 
   `mhr_org_id` string COMMENT '管户人归属机构ID', 
   `mhr_team_id` string COMMENT '管户人归属团队ID', 
   `mhr_team_name` string COMMENT '管户人归属团队名称', 
   `mhr_channel_id` string COMMENT '管户人归属渠道ID', 
   `mhr_channel_name` string COMMENT '管户人归属渠道名称', 
   `asset_level_manage_lm` string COMMENT '上月财富管理客户分层', 
   `asset_level_manage_ly` string COMMENT '上年财富管理客户分层', 
   `cust_1st_flag` string COMMENT '一类户标识', 
   `cust_2nd_flag` string COMMENT '二类户标识', 
   `cust_3rd_flag` string COMMENT '三类户标识', 
   `sk_new_flag` string COMMENT '双卡双新标识', 
   `jj_new_flag` string COMMENT '借记新户标识', 
   `xy_new_flag` string COMMENT '信用卡新户标识', 
   `fzh_flag` string COMMENT '分支行渠道标识', 
   `zk_flag` string COMMENT '重客标志', 
   `ccjlb_cust_flag` string COMMENT '传承俱乐部客户标志', 
   `ccjlb_agent_flag` string COMMENT '俱乐部会员标志', 
   `agent_no` string COMMENT '会员号', 
   `agent_pb_no` string COMMENT '会员所属金融顾问', 
   `agent_org_id` string COMMENT '会员所属机构', 
   `ccjlb_cust_list_add_type` string COMMENT '俱乐部私钻客户本年获客流失类型', 
   `potential_flag` string COMMENT '潜力菁英标志', 
   `agent_level` string COMMENT '会员等级', 
   `agent_yp_level` string COMMENT '会员预判等级', 
   `agent_asset_level` string COMMENT '会员财富层级', 
   `new_agent_flag` string COMMENT '本年新会员标志', 
   `agent_level_desc` string COMMENT '会员岗位描述', 
   `agent_status_desc` string COMMENT '会员在职状态(试用,在职,离职)', 
   `agent_post_flag` string COMMENT '会员离职标志', 
   `qualify_investor_flag` string COMMENT '客户合格投资者标签', 
   `qlsz_flag` string COMMENT '潜力私钻客户标志', 
   `t0_cust_flag` string COMMENT 'T0客户标志', 
   `t1_cust_flag` string COMMENT 'T1客户标志', 
   `t2_cust_flag` string COMMENT 'T2客户标志', 
   `mon_touch_flag` string COMMENT '本月接触标志', 
   `hold_bxjxt_flag` string COMMENT '保险金信托客户标志', 
   `pb_cust_manage_flag` string COMMENT '三点一线对齐客户标志', 
   `zj_pb_cust_manage_flag` string COMMENT '管户人是否综金PB标志', 
   `cf_asset_level_name` string COMMENT '财富管理分层名称', 
   `cust_asset_level_name` string COMMENT '客户资产分层名称', 
   `new_cust_flag` string COMMENT '本年新客标识', 
   `rj_flag` string COMMENT '是否入金', 
   `app_fst_login_date` string COMMENT '首次登录口袋APP的日期', 
   `qw_cust_flag` string COMMENT '是否企微客户', 
   `group_cust_type` string COMMENT '集团客户最高账户类型', 
   `qw_gh_flag` string COMMENT '是否管户客户(企微)', 
   `yb_flag` string COMMENT '是否银保客户', 
   `acct_vail_cust_flag` string COMMENT '账户有效客户标识', 
   `mtd_actv_cust_flag` string COMMENT '客户动账月活标志', 
   `qtd_actv_cust_flag` string COMMENT '客户动账季活标志', 
   `ytd_actv_cust_flag` string COMMENT '客户动账年活标志', 
   `iiact_uplvl_cust_flag` string COMMENT '二类户升级一类户客户标志', 
   `iiiact_uplvl_cust_flag` string COMMENT '三类户升级一类户客户标志', 
   `iiact_upopn_cust_flag` string COMMENT '二类户开立一类户客户标志', 
   `iiiact_upopn_cust_flag` string COMMENT '二类户开立一类户客户标志', 
   `nw_sw_desc` string COMMENT '客户管户内外勤标识', 
   `vail_cust_manager_flag` string COMMENT '真实(有效)管户人标识', 
   `cust_manager_ttk_flag` string COMMENT '厅堂宽口径', 
   `cust_manager_ttz_flag` string COMMENT '厅堂窄口径', 
   `quali_type_jj_flag` string COMMENT '客户管户是否基金持证', 
   `lcjl_flag` string COMMENT '理财金领_客群标志', 
   `djg_flag` string COMMENT '董监高_客群标志', 
   `cgjz_flag` string COMMENT '超高净值_客群标志', 
   `fyzln_flag` string COMMENT '富裕中老年_客群标志', 
   `jmsk_flag` string COMMENT '精明熟客客_客群标志', 
   `xqyz_flag` string COMMENT '小企业主_客群标志', 
   `ycyz_flag` string COMMENT '有车一族_客群标志', 
   `nqcr_flag` string COMMENT '年轻潮人_客群标志', 
   `cf_asset_level_range` string COMMENT '财富管理客户资产等级范围', 
   `mtd_pay_cust_flag` string COMMENT '财富管理客户资产等级范围', 
   `qtd_pay_cust_flag` string COMMENT '客户支付季活标志', 
   `ytd_pay_cust_flag` string COMMENT '客户支付年活标志', 
   `yb_five_star_lvl` string COMMENT '银保五星客户等级', 
   `shgh_flag` string COMMENT '是否私行中心管户', 
   `y_new_cust_flag` string COMMENT '本年新客标识(剔除无效户)', 
   `m_new_cust_flag` string COMMENT '本月新客标识(剔除无效户)', 
   `hold_card_type` string COMMENT '持卡类型', 
   `qr_new_flag` string COMMENT '汽融双新标识', 
   `qr_m_flag` string COMMENT '汽融客户标识(未结清或本年结清)', 
   `xj_new_flag` string COMMENT '消金双新标识', 
   `xj_m_flag` string COMMENT '消金客户标识(未结清或本年结清)', 
   `credit_channl_flag` string COMMENT '信用卡渠道', 
   `last_30d_login_flag` string COMMENT '口袋app活跃30天用户', 
   `gd5wy_cust_flag` string COMMENT '是否滚动5万元户', 
   `ds_cust_flag` string COMMENT '是否顶私客户', 
   `cust_asset_level_ds` string COMMENT '客户资产分层_顶私', 
   `hk_ls_type_mon` string COMMENT '顶私获客流失类型(较上月末)', 
   `hk_ls_type_year` string COMMENT '顶私获客流失类型(较上年末)', 
   `sh_gh_type` string COMMENT '私行管户类型', 
   `xyk_flag` string COMMENT '信用卡渠道标识T-2(双卡客户+信用卡MGM+被动注销)', 
   `zt_all_flag` string COMMENT '大综拓渠道标识T-2(综拓老渠道+一户通标识)', 
   `sd_flag` string COMMENT '收单渠道标识T-2', 
   `df_sub_lc_flag` string COMMENT '代发渠道标识T-2(客群)', 
   `kfyh_flag` string COMMENT '开放银行渠道标识T-2', 
   `wdjd_flag` string COMMENT '网点进店渠道标识T-2(本年)', 
   `yz_flag` string COMMENT '银证渠道标识T-2', 
   `non_zero_flag` string COMMENT '非零资产客户标识', 
   `ops_wdsthk_flag` string COMMENT '网点生态渠道标识', 
   `dt` date COMMENT 'dt')
         ENGINE=OLAP
DUPLICATE KEY(`cust_no`)
   PARTITION BY RANGE(`dt`)
                        (
                            PARTITION `p230201` VALUES LESS THAN ("2023-02-01"),
                            PARTITION `p230302` VALUES LESS THAN ("2023-02-02"),
                            PARTITION `p230303` VALUES LESS THAN ("2023-02-03")
                            )
DISTRIBUTED BY HASH(`cust_no`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
)